#!/bin/bash

check_err()
{
	if [ $1 -ne 0 ]; then
		echo $2 >&2
		exit 1
	fi
}

git diff-index --check --cached HEAD
check_err $? "Patch contains whitespace errors"

git diff --cached | scripts/checkpatch.pl --no-signoff -q -
check_err $? "Patch failed checkpatch"
