#!/bin/sh

check_err()
{
	if [ $1 -ne 0 ]; then
		echo $2 >&2
		exit 1
	fi
}

if [ ! -x "$(command -v smatch)" ]; then
	echo "Smatch is not in your patch. Aborting" >&2
	exit 1
fi

# Check if we actually have commits to push
commits=$(git log @{u}..)
if [ -z "$commits" ]; then
	exit 0
fi

echo "Compiling kernel"
make olddefconfig &> /dev/null
# Need these options for sparse to work
scripts/config -e CONFIG_UNWINDER_FRAME_POINTER
scripts/config -d CONFIG_RETPOLINE
scripts/config -d CONFIG_STACK_VALIDATION
make -j`nproc` &> /dev/null
check_err $? "Compilation failed"

echo "Running sparse"
test $(make C=2 CF="-D__CHECK_ENDIAN__" \
       M=drivers/net/ethernet/mellanox/mlxsw/ 2>&1 | egrep 'error|warn|info' | \
       tee /dev/tty | wc -l) -eq 0
check_err $? "Sparse failed"

echo "Running smatch"
test $(make CHECK="smatch -p=kernel" C=2 \
       M=drivers/net/ethernet/mellanox/mlxsw/ 2>&1 | \
       egrep 'error|warn|info' | tee /dev/tty | wc -l) -eq 0
check_err $? "Smatch failed"

echo "Running includecheck"
test $(make includecheck | egrep '*mlxsw*' | tee /dev/tty | wc -l) -eq 0
check_err $? "includecheck failed"

echo "Running checkstack"
test $(make checkstack M=drivers/net/ethernet/mellanox/mlxsw/ | grep mlxsw | \
       awk -F ':' '{ print $2 }' | head -n 1) -lt 512
check_err $? "checkstack failed"

exit 0
